server:
  port: 8085

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false