spring:
  security:
    oauth2:
      client:
        provider:
          okta:
            issuer-uri: https://dev-81589621.okta.com/oauth2/aus5c75vecVGNgenN5d7
        registration:
          okta:
            client-id: 0oa5c68bcsLHj3CEW5d7

hello-okta-api:
  client:
    run-as-details:
      client-id: ???
      client-secret: ???

springdoc:
  swagger-ui:
    oauth:
      client-id: 0oa5c68bcsLHj3CEW5d7